services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:Z
      - /app/node_modules # ← NOVA LINHA: exclui do volume
      - /app/.next # ← NOVA LINHA: exclui do volume
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/quimica_dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quimica_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
