services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app:Z
      - /app/node_modules
      - /app/.next
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/quimica_dev
      NEXTAUTH_SECRET: secret-temporario-desenvolvimento
      NEXTAUTH_URL: http://localhost:3000
      ADMIN_EMAIL: professor@exemplo.com
      ADMIN_PASSWORD_HASH: $$2a$$10$$Bltc8oGvgCdswyHxpj3eie.2rjSnwm0dx4UsUaMVfbj.LhJ0LOQDC
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quimica_dev
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
